#!/usr/bin/env bash
echo "put - object"
# Storing the files
OUTPUT_DIR="/tmp/s3-bash-scripts"

# new generation if doesnt already exist: 
rm -r $OUTPUT_DIR

# Creating output folder
mkdir -p $OUTPUT_DIR

# Generate random number
NUM_FILES=$((RANDOM % 6 + 5))

for ((i = 1; i <= NUM_FILES; i++)); do
  FILENAME="$OUTPUT_DIR/file_$i.txt"
  
  # Generate 100 random bytes of data and write it into the file
  head -c 100 /dev/urandom | base64 > "$FILENAME"

  echo "Created file: $FILENAME with random data"
done
